version: '3'

services:
  rclone:
    image: ghcr.io/luler/rclone_docker:latest
    restart: always
    volumes:
      - ./config/rclone.conf:/config/rclone/rclone.conf # rclone配置文件
      - ./config/crontab:/etc/crontab # 定时任务配置文件
      - ./data:/data  # 数据目录
      - ./logs:/var/log # 日志目录
